class Config {

    static applicationId = 'tech.ordinaryroad.android' // TODO applicationId
    static appName = 'OrdinaryRoadAucFrameTemplate' // TODO appName

    static compileSdkVersion = 30 // TODO compileSdkVersion
    static minSdkVersion = 23 // TODO minSdkVersion
    static targetSdkVersion = 30 // TODO targetSdkVersion
    static versionCode = 1 // TODO versionCode
    static versionName = '1.0.0'// E.g. 1.9.72 => 1,009,072 // TODO versionName

    static gradlePluginVersion = '7.0.4' // TODO gradlePluginVersion
    static kotlinVersion = '1.6.10' // TODO kotlinVersion


    // TODO 第三方依赖版本
    static utilcodex_version = '1.31.0'
    static free_proguard_version = '1.0.1'
    static extextview_version = '1.0.2'
    static vertical_tab_layout_version = '1.2.5'
    static badgeview_version = '1.1.3'
    static taptargetview_version = '1.13.0'
    static zxing_core_version = '3.4.0'
    static bga_qrcodecore_version = '1.1.7@aar'
    static bga_zxing_version = '1.1.7@aar'
    static biometric_prompt_version = '1.0'
    static circleimageview_version = '3.1.0'
    static ticker_version = '2.0.4'
    static srl_version = '2.0.5'
    static toasty_version = '1.5.2'
    static brvah_version = '3.0.7'
    static banner_version = '2.2.2'
    static material_dialogs_version = '3.3.0'
    static pannel_switch_helper_version = '1.4.0'
    static subsampling_scale_image_view_version = '3.10.0'
    static retrofit_version = '2.9.0'
    static leakcanary_android_version = '2.1'

    static depConfig = [
            /*Never delete this line*/
            /*Generated by "config.json"*/
            feature_mock               : new DepConfig(false, true , ":feature:mock"),
            feature_launcher_app       : new DepConfig(true , true , ":feature:launcher:app"),
            feature_feature0_app       : new DepConfig(true , true , ":feature:feature0:app"),
            feature_feature0_pkg       : new DepConfig(true , true , ":feature:feature0:pkg", "com.blankj:feature-feature0-pkg:1.0"),
            feature_feature0_export    : new DepConfig(true , true , ":feature:feature0:export"),
            feature_feature1_app       : new DepConfig(true , true , ":feature:feature1:app"),
            feature_feature1_pkg       : new DepConfig(true , true , ":feature:feature1:pkg"),
            feature_feature1_export    : new DepConfig(true , true , ":feature:feature1:export"),
            feature_template_app       : new DepConfig(true , true , ":feature:template:app"),
            feature_template_pkg       : new DepConfig(true , true , ":feature:template:pkg"),
            feature_template_export    : new DepConfig(true , true , ":feature:template:export"),
            lib_base                   : new DepConfig(true , true , ":lib:base"),
            lib_common                 : new DepConfig(true , true , ":lib:common"),
            lib_util                   : new DepConfig(true , true , ":lib:util"),
            lib_ui                     : new DepConfig(true , true , ":lib:ui"),
            lib_photoview              : new DepConfig(true , true , ":lib:photoview"),
            lib_api                    : new DepConfig(true , true , ":lib:api"),
            /*Never delete this line*/
//            feature_template_app       : new DepConfig(":feature:template:app"),
//            feature_template_pkg       : new DepConfig(":feature:template:pkg"),
//            feature_template_export    : new DepConfig(":feature:template:export"),
            plugin_gradle                 : new DepConfig(pluginPath: "com.android.tools.build:gradle:$gradlePluginVersion"),
            plugin_kotlin                 : new DepConfig(pluginPath: "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"),
            plugin_api                    : new DepConfig(pluginPath: "com.blankj:api-gradle-plugin:1.4", pluginId: "com.blankj.api"),
            plugin_bus                    : new DepConfig(pluginPath: "com.blankj:bus-gradle-plugin:2.6", pluginId: "com.blankj.bus"),

            // TODO 第三方依赖
            core_ktx                      : new DepConfig("androidx.core:core-ktx:1.3.2"),
            appcompat                     : new DepConfig("androidx.appcompat:appcompat:1.3.0"),
            material                      : new DepConfig("com.google.android.material:material:1.3.0"),
            constraintlayout              : new DepConfig("androidx.constraintlayout:constraintlayout:2.0.4"),
            lifecycle_livedata_ktx        : new DepConfig("androidx.lifecycle:lifecycle-livedata-ktx:2.3.1"),
            lifecycle_viewmodel_ktx       : new DepConfig("androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1"),
            lifecycle_viewmodel_savedstate: new DepConfig("androidx.lifecycle:lifecycle-viewmodel-savedstate:2.3.1"),
            navigation_fragment_ktx       : new DepConfig("androidx.navigation:navigation-fragment-ktx:2.3.5"),
            navigation_ui_ktx             : new DepConfig("androidx.navigation:navigation-ui-ktx:2.3.5"),
            preference_ktx                : new DepConfig("androidx.preference:preference-ktx:1.1.1"),
            viewpager2                    : new DepConfig("androidx.viewpager2:viewpager2:1.0.0"),
            recyclerview                  : new DepConfig("androidx.recyclerview:recyclerview:1.2.1"),
            support_multidex              : new DepConfig("com.android.support:multidex:1.0.2"),

            utilcodex                     : new DepConfig("com.blankj:utilcodex:$utilcodex_version"),
            free_proguard                 : new DepConfig("com.blankj:free-proguard:$free_proguard_version"),

            extextview                    : new DepConfig("com.lcodecorex:extextview:$extextview_version"),
            vertical_tab_layout           : new DepConfig("q.rorbin:VerticalTabLayout:$vertical_tab_layout_version"),
            badgeview                     : new DepConfig("q.rorbin:badgeview:$badgeview_version"),
            taptargetview                 : new DepConfig("com.getkeepsafe.taptargetview:taptargetview:$taptargetview_version"),
            // 二维码
            zxing_core                    : new DepConfig("com.google.zxing:core:$zxing_core_version"),
            bga_qrcodecore                : new DepConfig("cn.bingoogolapple:bga-qrcodecore:$bga_qrcodecore_version"),
            bga_zxing                     : new DepConfig("cn.bingoogolapple:bga-zxing:$bga_zxing_version"),
            // 生物识别
            biometric_prompt              : new DepConfig("com.github.ZuoHailong:BiometricPrompt:$biometric_prompt_version"),
            // Circle Image View
            circleimageview               : new DepConfig("de.hdodenhof:circleimageview:$circleimageview_version"),
            // Ticker View
            ticker                        : new DepConfig("com.robinhood.ticker:ticker:$ticker_version"),
            // Smart Refresh Layout
            refresh_layout_kernel         : new DepConfig("io.github.scwang90:refresh-layout-kernel:$srl_version"),
            refresh_header_material       : new DepConfig("io.github.scwang90:refresh-header-material:$srl_version"),
            refresh_footer_classics       : new DepConfig("io.github.scwang90:refresh-footer-classics:$srl_version"),
            // Toasty
            toasty                        : new DepConfig("com.github.GrenderG:Toasty:$toasty_version"),
            // brvah
            brvah                         : new DepConfig("com.github.CymChad:BaseRecyclerViewAdapterHelper:$brvah_version"),
            // Banner
            banner                        : new DepConfig("io.github.youth5201314:banner:$banner_version"),
            // Material Dialogs
            material_dialogs_core         : new DepConfig("com.afollestad.material-dialogs:core:$material_dialogs_version"),
            material_dialogs_lifecycle    : new DepConfig("com.afollestad.material-dialogs:lifecycle:$material_dialogs_version"),
            material_dialogs_input        : new DepConfig("com.afollestad.material-dialogs:input:$material_dialogs_version"),
            material_dialogs_datetime     : new DepConfig("com.afollestad.material-dialogs:datetime:$material_dialogs_version"),
            material_dialogs_bottomsheets : new DepConfig("com.afollestad.material-dialogs:bottomsheets:$material_dialogs_version"),
            // 解決键盘布局闪动
            panel_switch_helper           : new DepConfig("com.github.YummyLau:PanelSwitchHelper:$pannel_switch_helper_version"),
            // 大图
            subsampling_scale_image_view  : new DepConfig("com.davemorrissey.labs:subsampling-scale-image-view:$subsampling_scale_image_view_version"),

            // 网络请求retrofit
            retrofit                      : new DepConfig("com.squareup.retrofit2:retrofit:$retrofit_version"),
            retrofit_converter_gson       : new DepConfig("com.squareup.retrofit2:converter-gson:$retrofit_version"),

            leakcanary_android            : new DepConfig("com.squareup.leakcanary:leakcanary-android:$leakcanary_android_version")
    ]
}